"""add amount back

Revision ID: 068ab7462033
Revises: 5abe714887e9
Create Date: 2024-06-24 21:42:18.089211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068ab7462033'
down_revision = '5abe714887e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(precision=3), nullable=False))
        batch_op.create_index(batch_op.f('ix_water_usage_amount'), ['amount'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_usage_amount'))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
