"""add usage type to water usage table

Revision ID: 261c52424d0a
Revises: bc2be52de290
Create Date: 2024-06-24 17:07:50.164743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261c52424d0a'
down_revision = 'bc2be52de290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_type', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_column('usage_type')

    # ### end Alembic commands ###
