"""user table name

Revision ID: 3541fbbb1997
Revises: 261c52424d0a
Create Date: 2024-06-24 17:10:32.844807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3541fbbb1997'
down_revision = '261c52424d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
