"""amount -> time taken

Revision ID: 5abe714887e9
Revises: 3541fbbb1997
Create Date: 2024-06-24 21:31:25.461050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abe714887e9'
down_revision = '3541fbbb1997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.Float(precision=3), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('time_taken')

    # ### end Alembic commands ###
