"""index time taken water usage

Revision ID: 6cc71ed5d591
Revises: 068ab7462033
Create Date: 2024-06-24 22:09:38.494196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc71ed5d591'
down_revision = '068ab7462033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_usage_time_taken'), ['time_taken'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_usage_time_taken'))

    # ### end Alembic commands ###
