"""water usages table

Revision ID: bc2be52de290
Revises: 2c39002a0dc3
Create Date: 2024-06-24 10:43:22.486588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2be52de290'
down_revision = '2c39002a0dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_usage_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_usage_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_water_usage_timestamp'))

    op.drop_table('water_usage')
    # ### end Alembic commands ###
